import streamlit as st
import requests
import datetime
import traceback

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="✈️ Trip planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("✈️ Trip planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat prompt
st.header("How can I help you in planning a trip? Let me know where you want to visit.")

# Chat input form
with st.form(key="Trip_input_form"):
    user_input = st.text_input("User input:", placeholder="plan a trip to Paris for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Thinking..."):
            # ✅ Fixed key: must be "query"
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# ✈️ AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Created by:** Shiham's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify all information, especially prices and availability, before making any bookings.*
"""
            st.markdown(markdown_content)
        else:
            st.error(f"❌ Bot failed to respond ({response.status_code}):\n{response.text}")

    except Exception as e:
        st.error(f"❌ The operation failed due to: {e}")
        st.text(traceback.format_exc())
