import os
import datetime

def save_document(response_text: str, directory: str = "/.output"):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)
    
    # Create markdown content with metadata header
    markdown_content = f"""# ✈️ AI Travel Plan
    
    # **Generated on:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    # **Created by:** Shiham's Travel Agent
    
    ---
    
    {response_text}
    
    ---
    This travel plan was generated by an AI agent. Please verify all information, especially prices and availability, before making any bookings.
    """
    
    try:
        # write to markdown file with UTF-8 encoding
        # Generating timestamp filename
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{directory}/AI_Travel_Plan_{timestamp}.md"
        
        print(filename)
        
        with open(filename, "w", encoding="utf-8") as file:
            file.write(markdown_content)
            
        print(f"Markdown file saved successfully: {filename}")
        return filename
    
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None
    